esphome:
  name: esp-kb
  friendly_name: esp kb
  on_boot: 
      - delay: 60s
      - uart.write: [0x57,0xAB,0x00,0x02,0x08,0x00,0x00,0x3A,0x00,0x00,0x00,0x00,0x00,0x46]
#      - uart.write: [0x57,0xAB,0x00,0x03,0x04,0x02,0x04,0x00,0x00,0x0F]
      - uart.write: [0x57,0xAB,0x00,0x02,0x08,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x0C]
          
# D4 TX

esp8266:
  board: esp01_1m

# Enable logging
# logger:

# # Enable Home Assistant API
# api:
#   encryption:
#     key: "7lGFFhURLtRT2OW3kHGexEWU37arU/tf23KKJrL0ksg="

# ota:
#   - platform: esphome
#     password: "c591777021acec83b2a9aaba87e22d5f"

# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password

#   # Enable fallback hotspot (captive portal) in case wifi connection fails
#   ap:
#     ssid: "213 Fallback Hotspot"
#     password: "DBSOSdlNuxlY"

uart:
  rx_pin: GPIO12
  tx_pin: GPIO14
  baud_rate: 9600
#   debug:
#     direction: BOTH
#     dummy_receiver: false
#     after:
#       delimiter: "\n"
#     sequence:
#       - lambda: UARTDebug::log_string(direction, bytes);

# captive_portal:
    