esphome:
  name: wt32-sc01-plus
  friendly_name: WT32-SC01-PLUS

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "BUGUToHHTzuTuV9vXvGIA8m/WvMahU05gtT6a/d4PQA="

ota:
  - platform: esphome
    password: "09c1c7ecbabece43174c846b72fa0cc5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wt32-Sc01-Plus Fallback Hotspot"
    password: "StIxySh6Ek4f"

captive_portal:
    